### ISSUE TITLE
API Key requirement

### ISSUE THREAD

**Issue by Edgar-Ventura** [raybuhr/freeCurrencyApiR#1]
Hello,

Love this package. freeCurrencyAPI has just made it a requirement to use an API Key. Will you be able to add this requirement to the current package?

**Comment by raybuhr** [comment]
Thanks for the heads up @Edgar-Ventura 

I'll try to knock this out today/tomorrow.

**Comment by raybuhr** [comment]
I pushed an update that will pull the API key from an environment variable `FREE_CURRENCY_API_KEY` in requests and prompt the user if it is missing. I also added some documentation for how to set that. Everything else works the same.
